version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - my-db-data:/var/lib/postgresql/data
    networks:
      - skynet
    environment:
      POSTGRES_PASSWORD: realeyesrealizereallies
      POSTGRES_USER: localdev
      POSTGRES_DB: tourney
  adminer:
    image: adminer
    hostname: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    networks:
      - skynet
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    volumes:
      - $PWD/.sessionsData:/data
    networks:
      - skynet
  app:
    image: tourney_app:local
    container_name: tourney_app
    working_dir: /root/app
    # tty: true
    stdin_open: true
    # this tells docker compose not to pull from dockerhub, but instead build the image from the given docker file below
    build:
      context: $PWD
      dockerfile: $PWD/docker/dev/Dockerfile
    volumes:
      - tourney_app-sync:/root/app:nocopy
      # dirs to not sync over
      - /root/app/node_modules/
      - /root/app/coverage/
      - /root/app/build/
    env_file: ../../.env
    networks:
      - skynet
    ports:
      - '5001:5001'
      - '9229:9229'
volumes:
  # This is for the docker-sync container that gets started
  tourney_app-sync:
    external: true
  my-db-data:

networks:
  skynet: